apiVersion: batch/v1
kind: CronJob
metadata:
  name: simplecronjobfail
spec:
  # Run every 10 minutes. See https://en.wikipedia.org/wiki/Cron
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: simplepyscriptapp
            image: bmalevich/simplepyscriptappfail
          restartPolicy: OnFailure